version: 2.1

executors:
  go-executor:
    docker:
      - image: cimg/go:1.21

jobs:
  analyze:
    executor: go-executor
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y llvm curl

      - run:
          name: Run Analyzer
          command: make analyze-program

workflows:
  analyze-workflow:
    jobs:
      - analyze