version: 2.1

executors:
  go-executor:
    docker:
      - image: cimg/go:1.21
    resource_class: xlarge

jobs:
  analyze:
    executor: go-executor
    steps:
      - checkout

      - run:
          name: Install Dependencies via Mise
          command: |
            sudo apt-get update
            sudo apt-get install -y build-essential cmake ninja-build python3 curl git clang lld libc++-dev libc++abi-dev
        
      - run:
           name: Install Mise
           command: |
             curl -fsSL https://mise.jdx.dev/install.sh | sh
             echo $BASH_ENV
             echo 'export PATH="$HOME/.local/bin:$PATH"' >> $BASH_ENV
             echo 'export PATH="$HOME/.local/share/mise/shims:$PATH"' >> $BASH_ENV
             source $BASH_ENV
 
      - run:
           name: Install Dependencies via Mise
           command: |
             CC=clang CXX=clang++ mise install llvm-objdump@20.1.0
             mise use -g llvm-objdump@20.1.0

      - run:
          name: Run Analyzer
          command: make analyze-program

workflows:
  analyze-workflow:
    jobs:
      - analyze