version: 2.1

executors:
  go-executor:
    docker:
      - image: cimg/go:1.21

jobs:
  analyze:
    executor: go-executor
    steps:
      - utils/checkout-with-mise  # This handles checkout and mise dependencies

      - run:
          name: Install LLVM-Objdump via Mise
          command: |
            mise install llvm-objdump

      - run:
          name: Run Analyzer
          command: make analyze-program

workflows:
  analyze-workflow:
    jobs:
      - analyze